#!/bin/bash
# serve the blog for dev purposes: auto-refresh after each change.
trap 'kill $(jobs -p)' EXIT
./serve -postpath=docs "$@" &
pid=$!
while inotifywait -qqe close_write . docs; do
  kill -sint $pid
done
