app = "iio"
primary_region = "cdg"
kill_signal = "SIGTERM"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  requests.hard_limit = 1000
