#!/bin/sh
# install: ln -rs pre-commit .git/hooks/

if ! git diff -u pubdates.cache <(go run blog/pubdates -postpath=docs); then
  go run blog/pubdates -postpath=docs >pubdates.cache
  echo "pubdates cache fixed, rerun git commit."
  exit 1
fi

if test -z "$skiptests" && git diff-index --name-only --cached HEAD | grep -q '\.go$'; then
  echo -n 'testing... (use `skiptests=1 git commit` to skip)'
  go test ./... >/tmp/.blogtests 2>&1
  result="$?"
  echo -en "\r\e[K"
  if test "$result" -ne 0; then
    echo 'tests failed (use `skiptests=1 git commit` to skip): go test ./...'
    cat /tmp/.blogtests
    exit "$result"
  fi
fi
