#!/bin/dash
set -e
checkmode="-c"
if test "$1" = "-f"; then
  checkmode=""
else
  trap 'echo use "./precommit -f" to fix' EXIT
fi
./genfrontpage $checkmode
./genrss $checkmode
./htmlize $checkmode -r -o docs/index.html
./htmlize $checkmode -n 4 -o docs/latest
./gopherize $checkmode
trap '' EXIT
if ! test $(cat docs/latest | wc -c) -lt 100000; then
  echo docs/latest too big. make a filler article.
  exit 1
fi
