name: backup
on: [push]
jobs:
  backup:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: go setup
        run: |
          echo "GOROOT=$GOROOT_1_16_X64" >>$GITHUB_ENV
          echo "$GOROOT_1_16_X64/bin" >>$GITHUB_PATH
      - name: git setup
        run: |
          cd
          echo >>.netrc -e "machine github.com\nlogin $GITHUB_ACTOR\npassword $GITHUB_TOKEN"
          echo >>.netrc -e "machine api.github.com\nlogin $GITHUB_ACTOR\npassword $GITHUB_TOKEN"
          chmod 600 .netrc
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git config --global pull.rebase true
      - run: git clone -b backup https://github.com/ypsu/blog.git .
      - run: git pull --rebase=false origin master
      - run: go run serve.go -postpath docs -dumpall >docs/index.html
      - run: git diff --quiet || git commit -avm "regen the backup"
      - run: git push
