name: update

on:
  push:
    branches: [main]

jobs:
  reload:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: pull changes on the live server
        run: curl -s https://iio.ie/reloadposts
